### ISSUE TITLE
Documentation on hardware constraint specification

### ISSUE THREAD

**Issue by AdriaanRol** [QuTech-Delft/OpenQL#175]
It is currently possible to specify certain hardware constraints in the config files. It is unclear how these are interpreted and taken into account. It is quite important to understand how these affect scheduling. This should be documented.

**Comment by MiguelSMoreira** [comment]
I believe @wvlothuizen comment on issue #274 (regarding CCL hardware configuration) should be taken into account here as well since it pertains to how the configuration file should be structured not only for CCL but in general. The comment also presents several good examples of things that should be restructured in this file, to make it more readable and clear.

I quote the original post:
> file 'doc/configuration_specification_cc.md' contains CC specifics on configuration, but also comments on the generic part of OpenQL specifications that I learned when working on the source, e.g. parameters that occur in many JSON files but are not actually implemented.
In addition to documenting what's there, I would also like to make a case for restructuring the JSON file in a way that clarifies which parts are used by which feature, and makes unused parts optional.
As an example, keys 'resources' and 'topology' are both used by the resource constrained scheduler only, but still need to be present if that is not used. As a second example, a 'matrix' must always be provided, event though it is only used in particular cases (never in DiCarlo lab), also see #123

**Comment by imranashraf** [comment]
IMHO we should deal with restructuring separately and not here. First step is to document what is there. then comes the discussion separte issue/PR dealing with making things optional.
