### ISSUE TITLE
Slow compilation due to inclusion of Eigen

### ISSUE THREAD

**Issue by anneriet** [QuTech-Delft/OpenQL#317]
Because the complete Eigen library is included as a submodule, building OpenQL has become very slow. While this is not necessary, because only some of the header files of Eigen are needed for unitary decomposition and other algorithms.

**Comment by jvansomeren** [comment]
A make of the OpenQL from scratch on my old Linux CentOS work station takes about 20 minutes.
That takes too long so I'm looking for ways to reduce that.

You @anneriet wrote that the complete Eigen library is included but that only some of the header files are needed for unitary decomposition in the OpenQL compiler.
Could you try to update making unitary decomposition so that it doesn't use the complete Eigen library?

**Comment by anneriet** [comment]
I'm working on it, when only the necessary parts of the eigen library are included, the compilation time is about halved, so that would be 10 mins for you. That's better but still too long, so I am looking into other things (like pre-compilation), I'll open a pull-request once I've got something that is a significant enough improvement.

**Comment by wvlothuizen** [comment]
Seems to be solved in 0.10.0
